/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'
import { Route as HomeSettingImport } from './routes/home/setting'
import { Route as HomeProfileImport } from './routes/home/profile'
import { Route as HomePostsImport } from './routes/home/posts'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeSettingRoute = HomeSettingImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => HomeRoute,
} as any)

const HomeProfileRoute = HomeProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRoute,
} as any)

const HomePostsRoute = HomePostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => HomeRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof rootRoute
    }
    '/home/posts': {
      id: '/home/posts'
      path: '/posts'
      fullPath: '/home/posts'
      preLoaderRoute: typeof HomePostsImport
      parentRoute: typeof HomeImport
    }
    '/home/profile': {
      id: '/home/profile'
      path: '/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof HomeProfileImport
      parentRoute: typeof HomeImport
    }
    '/home/setting': {
      id: '/home/setting'
      path: '/setting'
      fullPath: '/home/setting'
      preLoaderRoute: typeof HomeSettingImport
      parentRoute: typeof HomeImport
    }
  }
}

// Create and export the route tree

interface HomeRouteChildren {
  HomePostsRoute: typeof HomePostsRoute
  HomeProfileRoute: typeof HomeProfileRoute
  HomeSettingRoute: typeof HomeSettingRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomePostsRoute: HomePostsRoute,
  HomeProfileRoute: HomeProfileRoute,
  HomeSettingRoute: HomeSettingRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/home/posts': typeof HomePostsRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/setting': typeof HomeSettingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/home/posts': typeof HomePostsRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/setting': typeof HomeSettingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/home/posts': typeof HomePostsRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/setting': typeof HomeSettingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/home/posts'
    | '/home/profile'
    | '/home/setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/home/posts'
    | '/home/profile'
    | '/home/setting'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/home/posts'
    | '/home/profile'
    | '/home/setting'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/(auth)/login",
        "/(auth)/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home.tsx",
      "children": [
        "/home/posts",
        "/home/profile",
        "/home/setting"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx"
    },
    "/home/posts": {
      "filePath": "home/posts.tsx",
      "parent": "/home"
    },
    "/home/profile": {
      "filePath": "home/profile.tsx",
      "parent": "/home"
    },
    "/home/setting": {
      "filePath": "home/setting.tsx",
      "parent": "/home"
    }
  }
}
ROUTE_MANIFEST_END */
